import { RenderProps } from "./types";

/**
 * A small, self contained example so Remotion Studio loads without running the
 * pipeline. The CLI render always overrides this with --props. The referenced
 * files live in public/sample (generated by `npm run setup:sample`).
 */
const defaultProps: RenderProps = {
  width: 640,
  height: 360,
  fps: 24,
  durationInFrames: 96,
  voiceover: "sample/vo.wav",
  music: "sample/music.wav",
  transitionSfx: "sample/whoosh.wav",
  musicVolume: 0.08,
  accentColor: "#09f097",
  titleCard: {
    text: "Sample Title",
    subtitle: "Content Engine",
    startFrame: 0,
    durationFrames: 60,
  },
  scenes: [
    {
      index: 0,
      startFrame: 0,
      durationFrames: 48,
      asset: { kind: "image", path: "sample/scene_00.jpg" },
      transition: { type: "crossfade", durationFrames: 14 },
      motion: { type: "ken-burns", params: { zoom: 1.12, direction: "in" } },
      lowerThird: null,
      query: "sample image",
    },
    {
      index: 1,
      startFrame: 48,
      durationFrames: 48,
      asset: { kind: "image", path: "sample/scene_01.jpg" },
      transition: { type: "slide", durationFrames: 12 },
      motion: { type: "ken-burns", params: { zoom: 1.1, direction: "out" } },
      lowerThird: {
        text: "Lower Third",
        subtitle: "example",
        startFrame: 8,
        durationFrames: 32,
      },
      query: "sample image two",
    },
  ],
};

export default defaultProps;
